// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW6eVqiCkJj-X01IQ37qBq9au2DpvyJok',
    appId: '1:658320308322:web:f3911724e9dce7f43cb93b',
    messagingSenderId: '658320308322',
    projectId: 'fir-rivanbytarun',
    authDomain: 'fir-rivanbytarun.firebaseapp.com',
    storageBucket: 'fir-rivanbytarun.firebasestorage.app',
    measurementId: 'G-WZ79MMNKB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIxN2VItpTiMhwWPEfR8S91lxEQ1jbAYk',
    appId: '1:658320308322:android:36c18bd55228835a3cb93b',
    messagingSenderId: '658320308322',
    projectId: 'fir-rivanbytarun',
    storageBucket: 'fir-rivanbytarun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVA6xMkTJW9gB5VSOSiLhY5G5eLaOGybg',
    appId: '1:658320308322:ios:3f560003cbeeb46e3cb93b',
    messagingSenderId: '658320308322',
    projectId: 'fir-rivanbytarun',
    storageBucket: 'fir-rivanbytarun.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVA6xMkTJW9gB5VSOSiLhY5G5eLaOGybg',
    appId: '1:658320308322:ios:3f560003cbeeb46e3cb93b',
    messagingSenderId: '658320308322',
    projectId: 'fir-rivanbytarun',
    storageBucket: 'fir-rivanbytarun.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW6eVqiCkJj-X01IQ37qBq9au2DpvyJok',
    appId: '1:658320308322:web:d257c5cbea162b903cb93b',
    messagingSenderId: '658320308322',
    projectId: 'fir-rivanbytarun',
    authDomain: 'fir-rivanbytarun.firebaseapp.com',
    storageBucket: 'fir-rivanbytarun.firebasestorage.app',
    measurementId: 'G-JEFGQTDT1P',
  );
}
